### ISSUE TITLE
Tablet / mobile device wont enlarge or delete pics, vanilla bootstrap / file upload

### ISSUE THREAD

**Issue by flumpet** [kasperisager/vanilla-bootstrap#110]
Hi, 

I hope this is the correct place to post my query. I am using Vanilla 2.1 with Bootstrap 2.3 and the latest FileUpload-Version 1.8. After a fix from kasperisager to make the delete dialogue box show it's all working fine now on the pc. 

The issue i am having is that on a tablet or mobile I cant click on a thumbnail to make it larger or delete either. 

It wont click to go larger, it just doesn't do anything. I can hold down and choose open in a new window but i don't think our members will know to do that. 

The delete button is hovering over the italics button by the text box and it places italic <i><i> in the box instead. 

Is there anything I can do to fix this or has anyone found a fix for this please? I have tested this on an ipad / iphone and kindle fire hd and it is the same on all three devices. 

Thank you hugely in advance! 

Melanie

**Comment by kasperisager** [comment]
Closing as the project won't receive further updates until the release of Bootstrap 4.
