### ISSUE TITLE
Consider Putting user thumbs in panel header?

### ISSUE THREAD

**Issue by LucasKA** [kasperisager/vanilla-bootstrap#116]
I really want to use this theme as the entire theme for the site, but it still has some issues on mobile, a low hanging fruit would be to put the user thumbnail images in the panel header of the comment. 

Would give a ton more space to the comment width.

![screenshot 2014-09-08 09 51 10](https://cloud.githubusercontent.com/assets/1824267/4189042/60eb37f0-3778-11e4-9b6c-ad3096e4a611.png)

**Comment by kasperisager** [comment]
Closing as the project won't receive further updates until the release of Bootstrap 4.
