### ISSUE TITLE
Can't see close button and Wordpress comment embed is weird

### ISSUE THREAD

**Issue by gogito** [kasperisager/vanilla-bootstrap#127]
So, this is what I wanna report:
The close button for some flyout is like invisible
The embed comment in Wordpress is not right
Can you fix these ? And also, great theme (if not the best )
![comment](https://cloud.githubusercontent.com/assets/9802461/5071612/0b297c14-6ea5-11e4-94df-51f3770796da.PNG)
![no close bit](https://cloud.githubusercontent.com/assets/9802461/5071613/0b2d24ea-6ea5-11e4-98fd-672d9ac246ac.PNG)
![no close](https://cloud.githubusercontent.com/assets/9802461/5071614/0b3ec024-6ea5-11e4-80eb-16bd4fe95ceb.PNG)

**Comment by kasperisager** [comment]
A fix for the first point will be out as of v2.4.0. As for the embed comments, this will be included alongside mobile optimisations in a later release.
