### ISSUE TITLE
Issues with pupups  (modals) and dropdown menus

### ISSUE THREAD

**Issue by zhlousek** [kasperisager/vanilla-bootstrap#131]
Hi, 
Using vanilla 2.1.6.7 with flatly

I experience 2 issues even on a fresh install

1) Popups (modals) appear to not have the close button and even clicking outside the popup does not close it.

2) Dropdown menus (Me for example) do not close if if you click somewhere on the page. To close them you need to click on the link that opens the dropdown.

Neither is the behavior I experience with bootstrap in general. 

Do you know a simple way to change this behavior. 

Otherwise, thanks for the great work and bringing bootstrap themes to Vanilla

**Comment by kasperisager** [comment]
A fix for 1) is ready for v2.4.0. As for 2), this is due to a bug in Vanilla that I fixed sometime last year. It should be out as of Vanilla 2.3.
