### ISSUE TITLE
no scroll on sign-in pop up window on Android

### ISSUE THREAD

**Issue by twirk** [kasperisager/vanilla-bootstrap#132]
Thanks for a fantastic theme for VanillaForums!

One issue is on Android, when trying to sign in. The background behind the pop up window scrolls instead of the content of the pop up window. This hinders the user from clicking the sign in button.

Problematic. I hope you have time to look at it.

Thanks!

p.s.
• Vanilla 2.1.6
• Bootstrap Theme 2.3.4.

**Comment by kasperisager** [comment]
Sorry about the delay in responding to this! I recently came across this issue while working on another project built on Bootstrap for Vanilla and will have a fix out ASAP.

**Comment by kasperisager** [comment]
Closing as the project won't receive further updates until the release of Bootstrap 4.
