### ISSUE TITLE
Dropdown notification close itself when right click link on Firefox

### ISSUE THREAD

**Issue by chrisfebian** [kasperisager/vanilla-bootstrap#140]
When using Firefox, dropdown notification will close itself when right click the link
However this problem is not happened on other browser

**Comment by kasperisager** [comment]
Can you verify that this is specific to the Bootstrap theme?w

**Comment by 4311021x** [comment]
Yes I see this issue too.

**Comment by kasperisager** [comment]
Is the behaviour also observed when the default theme is used?

**Comment by 4311021x** [comment]
You mean Bootstrap Standard in theme options? Yes it happens with that one as well. And it happens only when you right click on a link. It doesn't happen when you right click on normal text.

**Comment by kasperisager** [comment]
I mean the Vanilla default theme. This is to check if the issue is specific to the Bootstrap theme and not Vanilla in general.

**Comment by 4311021x** [comment]
Ah okay it happens with the Vanilla default theme and on vanillaforums.org as well. So I guess you're using the Vanilla way to display dropdowns and not the [Bootstrap way](http://getbootstrap.com/examples/navbar/)?

**Comment by kasperisager** [comment]
Yep, all dropdowns are handled by Vanilla. Closing as a non-theme issue.
