### ISSUE TITLE
[Bootstrap] CSS Classes - Broken ul#navbar-nav children

### ISSUE THREAD

**Issue by Sicnus** [kasperisager/vanilla-bootstrap#142]
I think that's the proper term. I've included a screenshot where you can see that instead of the CSS being class="Categories", class="Discussions", class="Activity" it's setup as class>Categories and class>Discussions etc...

http://i.imgur.com/m9MDGBA.png

**Comment by kasperisager** [comment]
That's entirely valid HTML, no issue here :+1: When an attribute is added without a value it's implicitly `true`.
