### ISSUE TITLE
Some things are broken?

### ISSUE THREAD

**Issue by milezteg** [kasperisager/vanilla-bootstrap#143]
Vanilla: 2.1.8p2.
Bootstrap:  2.4.0

Did the full install with nodejs, bower, npm etc.  Worked without errors.

When I install I use the default Bootstrap theme and these problems are apparent:

* Sign In button freezes the page.  Requires refresh.
* Delete a post does not work (same as above, freezes page)

Anyone else seeing these problems?

**Comment by kasperisager** [comment]
Sounds like you have an JS conflict with another plugin. First step in debugging the issue would be checking your browser console for errors.

**Comment by larp-welt** [comment]
Hi!

Same to me... maybe a problem with jQuery 1.7.2? That's what my Vanilla uses!

Thank you!

**Comment by kasperisager** [comment]
My comment above still applies; you'll need to check your browser console for errors.

**Comment by CrazyLemon** [comment]
I can confirm that things are broken with 2.4.0 and vanilla 2.1.8p2. My width on the front page is now 10.000px . Investigating that right now.
I also got jquery error about version mismatch (vanilla wants 1.9.2) so i replaced custom.js with 2014 version (from july?). And no more jquery error in browser console.

**Comment by CrazyLemon** [comment]
I can confirm there is 10000px width in every .css.

:~/Desktop/vanilla-bootstrap-2.4.0$ grep -roP ".{0,30}width:10000" .
./design/custom_darkly.css:Meta,.BlockColumn .BlockTitle{width:10000
./design/custom_yeti.css:Meta,.BlockColumn .BlockTitle{width:10000
./design/custom_flatly.css:Meta,.BlockColumn .BlockTitle{width:10000

and so on. Hope this is useful info and that i'm not spamming :)

**Comment by kasperisager** [comment]
I'm investigating. Could you open up a new issue? The width bug is not JS related.

**Comment by RockAndRollStudioApps** [comment]
I´ve got the same problem, when I click on the sign button, the page freezes. Nice work btw!

Vanilla: 2.1.8p2.
Bootstrap: 2.4.0

**Comment by kasperisager** [comment]
Found the cause of the JS issue: A check was added in Bootstrap 3.3 to ensure that jQuery 1.9.1 and above is used (twbs/bootstrap#14852). Since Vanilla 2.1 still uses jQuery 1.7.2 this check will fail and JS execution will choke.

Since none of the Bootstrap JS components are used I'll simply remove them which should solve the issue.

**Comment by kasperisager** [comment]
Let me know if it works now!

**Comment by RockAndRollStudioApps** [comment]
Thanks allot, now it works! You´re awesome :)
