### ISSUE TITLE
.BlockColumn .BlockTitle width is 10000px on VB 2.4.0

### ISSUE THREAD

**Issue by CrazyLemon** [kasperisager/vanilla-bootstrap#144]
So like i copied in issue 143 there are a few design issues in vanilla bootstrap 2.4.0 (on vanilla 2.1.8p2).
First and most noticable is .BlockColumn .BlockTitle width is 10000px as is .BlockColumn .Meta.

~/Desktop/vanilla-bootstrap-2.4.0$ grep -roP ".{0,30}width:10000" .
./design/custom_darkly.css:Meta,.BlockColumn .BlockTitle{width:10000
./design/custom_yeti.css:Meta,.BlockColumn .BlockTitle{width:10000
./design/custom_flatly.css:Meta,.BlockColumn .BlockTitle{width:10000

The second issue is display: table-cell for .BlockColumn .BlockTitle because overflows the tables tbody.

**Comment by kasperisager** [comment]
Bootstrap 3.3 introduced some media object changes that has caused issues in the theme. I'm working on fixes right now.

**Comment by kasperisager** [comment]
Let me know if that did the trick!

**Comment by RockAndRollStudioApps** [comment]
Nah, it didn´t for me :p

**Comment by CrazyLemon** [comment]
It did the trick! Thank you for a quick fix! Great job with the theme btw.

I didnt see any design issues on activity tab but i can see the width: 10000px there.
.media-body,.Media-Body,.Item.Activity .ItemContent,.Item.ActivityComment .ItemContent{width:10000px}

So like i said no visible issues for me but that might cause issues for others.

**Comment by kasperisager** [comment]
Great, glad it worked out! The width is in there to compensate for cases where the media body doesn't take up the entire width of its parent (twbs/bootstrap#15391). This will cause issues when the display property of the media body is set to `block`, which is what was happening in the theme.
