### ISSUE TITLE
Navbar Collapse does not work

### ISSUE THREAD

**Issue by iStefo** [kasperisager/vanilla-bootstrap#145]
Hi, thanks for this great theme!

Unfortuntely, I noticed that the navbar's collapse toggle doesn't work in compact layout. There is just nothing happening.

Also, `$.fn.collapse` is undefined (which probably is the immediate reason for this problem), but I am wondering why this is happening? Files were simply loaded from http://vanillaforums.org/addon/bootstrap-theme and then added to `/themes`.

**EDIT**: This happens to version 2.5.0, will try with 2.4.0 to see if this is a regression.
**UPDATE**: 2.4.0 fails with "Bootstrap requires jQuery version 1.9.0 or higher". Am I doing something wrong?

**Comment by kasperisager** [comment]
Man, Bootstrap 3.3 really did some damage :frowning: The JS components were removed from the theme in 2.5.0 as the jQuery requirement was causing issues. Check out the release page for more info: https://github.com/kasperisager/vanilla-bootstrap/releases

I'd recommend loading the JS components of a previous release of Bootstrap (3.2 and below) as a workaround if you're using the theme as your mobile template as well.

**Comment by joseamirandavelez** [comment]
Ok I guess I have to download Bootstrap 3.2 copy the js file somewhere to the server and load it. But where should I put this script call? What file?

**Comment by kasperisager** [comment]
Simply loading the file is sufficient.

**Comment by joseamirandavelez** [comment]
I know, but in what file should I put the script tag? Sorry to bother but I
really don't know...

**Comment by kasperisager** [comment]
Ah, that would be `default.master.tpl`. No worries!

**Comment by joseamirandavelez** [comment]
Thanks man!
