### ISSUE TITLE
Darkly theme – default background of reply window makes the type invisible

### ISSUE THREAD

**Issue by Goalist** [kasperisager/vanilla-bootstrap#147]
Hi Kasper, 

First of all thank you very much for your awesome work on the bootstrap themes. It makes our lives so much easier! And they look beautiful – specially Darkly :)

I've noticed that in Darkly theme the default background of reply window is white and type is also set to white. That makes the content visible only on hover (when the background changes to dark grey). Do you have any suggestions how to get around it? 

Thanks again
Anna

**Comment by kasperisager** [comment]
Thanks heaps for compliments, I'm glad you like the theme! As for your issue, what you're seeing is definitely a bug. I'll have a look at it ASAP.

**Comment by kasperisager** [comment]
Closing as the project won't receive further updates until the release of Bootstrap 4.
