### ISSUE TITLE
Check boxes inverted

### ISSUE THREAD

**Issue by joseamirandavelez** [kasperisager/vanilla-bootstrap#148]
When I'm logged in as an admin there are some checkboxes next to the posts. If I check it nothing happens, but if I then unchecked it a menu appears at the bottom with options to delete, join or move the post. The menu should appear when the items are checked.

**Comment by CrazyLemon** [comment]
Check https://github.com/kasperisager/vanilla-bootstrap/issues/112 . Its fixed in Vanilla 2.3 - meanwhile you can use the fix from andersju - i can confirm that it works.

**Comment by joseamirandavelez** [comment]
That worked. Thanks!
