### ISSUE TITLE
The Navbar on mobile no longer works

### ISSUE THREAD

**Issue by imnotjames** [kasperisager/vanilla-bootstrap#150]
This is a side affect of 9a4c3e353d84e388791403fcd33f0652cfaff37d

Pretty easy fix.   Will be trying to fork + open a pull request fixing the funtionality today?

**Comment by kasperisager** [comment]
There's a very good reason for that change. Check out the release notes: https://github.com/kasperisager/vanilla-bootstrap/releases/tag/v2.5.0

Duplicate of #146, #145.
