### ISSUE TITLE
Recommended way of showing the loading spinner?

### ISSUE THREAD

**Issue by bleistivt** [kasperisager/vanilla-bootstrap#151]
Is there a recommended way to show the loading animation?

In the vanilla default I would just do it by adding a ``<span class="Progress"/>`` element, but that doesn't seem to have any rules attached to it.

Thanks for your great work with this theme.

**Comment by kasperisager** [comment]
Spinners are attached using Spin.js on-demand. You can find a few examples here: https://github.com/kasperisager/vanilla-bootstrap/blob/master/js/src/main.js#L18-L49

**Comment by bleistivt** [comment]
thanks!
