### ISSUE TITLE
Custom CSS should come AFTER Theme CSS

### ISSUE THREAD

**Issue by zel777** [kasperisager/vanilla-bootstrap#152]
I've noticed when editing the custom.css file that the overrides do not work, so I viewed the source code and the custom.css is not in the right order to override the default template styles.

The CSS in your theme goes in this order:
style.css
custom.css
custom_cerulean.css

It should go:
style.css
custom_cerulean.css
custom.css

**Comment by kasperisager** [comment]
This is how Vanilla loads stylesheets; it's not related to the theme.

**Comment by zel777** [comment]
Ok, I'll let them know about the issue. Thanks
