### ISSUE TITLE
PasswordStrength height is not enough?

### ISSUE THREAD

**Issue by df-5** [kasperisager/vanilla-bootstrap#153]
![chrome-1](https://cloud.githubusercontent.com/assets/10857464/6521619/da86fcbe-c38e-11e4-9328-e8b42f81ab40.png)

Not too sure where/how you're generating custom_*.css, but I'm currently overriding it in custom.css with this:
` div.PasswordStrength { height: 20px }`

The default appears to be `10px` as part of `.progress, .PasswordStrength{}`, the theme is custom_flatly.

**Comment by kasperisager** [comment]
This should probably be reported as a bug in the Bootswatch repo. Per the Bootstrap documentation, progress bars are supposed to be able to accept text input, which apparently doesn't work in Flatly.

**Comment by ArkQA** [comment]
It [Bootswatch] seems to accept it by default on virtue of it being a much much smaller font-size: http://jsfiddle.net/rb6nnq1t/

**Comment by kasperisager** [comment]
Ah, then it indeed is an issue with the theme.

**Comment by ArkQA** [comment]
Seems to hit yeti too:

![image](https://cloud.githubusercontent.com/assets/10857464/6530890/8ffc0b02-c3e9-11e4-9c25-d806b6477c14.png)

**Comment by kasperisager** [comment]
Closing as the project won't receive further updates until the release of Bootstrap 4.
