### ISSUE TITLE
Issues with Less

### ISSUE THREAD

**Issue by Awstein** [kasperisager/vanilla-bootstrap#154]
Hi Kasper,

I'm very sorry, this is going to be a noob question. I have been trying to make sense of your less files (first time reading/writing less, I am familiar with css though.) You seem to have a lot of variables in them but I was unable to find where exactly you set those variables. The variables.less file has almost nothing in it.
I need to adapt the theme to my company's graphic charter so am looking for enlightenment. 

Thanks in advance for your help!

**Comment by kasperisager** [comment]
Hi there! Most variables used are defined in the Bootstrap LESS files, i.e. here: https://github.com/twbs/bootstrap/blob/master/less/variables.less

**Comment by Awstein** [comment]
Thank you! That's what I thought at first but I tweaked them a bit and that didn't seem to elicit a response.
I am also having troubles with the npm install (SSL Error: CERT_UNTRUSTED) so that might partly account for why it didn't work, I guess.

Because of the latter I thought that some of the variables might also be stored in the bower_components folder (which is not installed at the moment, then, but I'm on my way to fixing that.) Am I right in thinking so?

Thanks again for the quick reply!

**Comment by Awstein** [comment]
Ok I think I've found the required files - they seem to have been in bower_components indeed.
I do have one last question. I have made some modifications on the file pertaining to the theme I use (bootswatch/simplex/variables.less) but when I launch gulp watch, it does not seem to recompile for the changes. I guess there is something I am doing wrong but I cannot for the life of me figure out what...

Thank you in advance for your help.

**Comment by Awstein** [comment]
Ok I think I have solved most of the issue.
I have one last question though: I'd like to get rid of the sign-in/sign-out button in the menu, as the forum is embedded in my website. But all I find in default.master.tph is {dashboard_link}
I'd like to keep most of it but not the sign it/out. Is there any way to do that? Thank you!
