### ISSUE TITLE
http github links blocked by modern browsers if domain is https

### ISSUE THREAD

**Issue by silabsoft** [kasperisager/vanilla-bootstrap#155]
Modern browsers will block both

            <iframe src="http://ghbtns.com/github-btn.html?user=kasperisager&type=follow" allowtransparency="true" frameborder="0" scrolling="0" width="145" height="20" style="vertical-align:top;margin-left:20px;"></iframe>
            <iframe src="http://ghbtns.com/github-btn.html?user=kasperisager&repo=vanilla-bootstrap&type=star&count=true" allowtransparency="true" frameborder="0" scrolling="0" width="85" height="20" style="vertical-align:top;"></iframe>

if the site is using a SSL certificate

change to // to fix the error. http://www.paulirish.com/2010/the-protocol-relative-url/

**Comment by kasperisager** [comment]
Good catch! I'll change the URLs to use HTTPS instead:

> 2014.12.17: Now that SSL is encouraged for everyone and doesn’t have performance concerns, this technique is now an anti-pattern. If the asset you need is available on SSL, then __always__ use the https:// asset.
