### ISSUE TITLE
There is __MACOSX directory present in archive on vanillaforums.org

### ISSUE THREAD

**Issue by TiGR** [kasperisager/vanilla-bootstrap#159]
What subject says.

This is a minor thing, but it would be nice to have no OS leftovers in release archives. Release source archives here on github do not have any extra files.

**Comment by kasperisager** [comment]
The version released on vf.org requires some extra modifications to avoid issues with folder naming and whatnot. I therefore have to modify the git-created archive locally prior to upload and have been too lazy to use `zip` so far; I'll ditch the built-in OS X compression feature for the next release :+1:

**Comment by fredghostkyle** [comment]
I believe that this happens when compressing things. You can remove it, nothing would change. It's just the way Apple likes compressing thing in their own special way.
