### ISSUE TITLE
You should rename to vanilla-forum-bootstrap

### ISSUE THREAD

**Issue by thednp** [kasperisager/vanilla-bootstrap#161]
People are looking for vanilla javascript for bootstrap or native javascript for bootstrap and get to your project, which is both confusing and inefficient.

BTW, you may be interested in something related to <a href="https://github.com/thednp/Native-Javascript-for-Bootstrap">the above keywords</a>.

**Comment by kasperisager** [comment]
`vanilla-forum-bootstrap` makes me uncomfortable. `vanilla-bootstrap` doesn't.

In all seriousness, I dare say that the description makes it pretty what this thing is:

> Kickstart your Vanilla-powered community forums with a fresh and solid theme that is ready to be customized to your heart's desires.
