### ISSUE TITLE
How to edit CSS properly?

### ISSUE THREAD

**Issue by Zach443** [kasperisager/vanilla-bootstrap#163]
I went to edit custom_darkly.css and I noticed that the file was uglified. Upon undoing that format, I became aware of the fact that that CSS file is over 23,000 lines long. I'm quite amazed that my editor did not crash when I pasted that in. I don't understand how you could possibly work productively with a file that large. Am I missing something, or was that file really not meant to be edited? All I need to do is change a few colors..

**Comment by kasperisager** [comment]
All of the CSS is generated from LESS files. The LESS for the Darkly theme is located here: https://github.com/kasperisager/vanilla-bootstrap/blob/master/less/themes/darkly.less. Once you've made your changes you will need to recompile the LESS files according to the instructions here: https://github.com/kasperisager/vanilla-bootstrap#development

**Comment by Zach443** [comment]
Ok, I have now edited <b>$body-bg</b> from the _variables.scss file in the Darkly folder. I saved, and built with npm. Nothing has changed on the site.

**Comment by xorith** [comment]
That LESS file imports other files. It can get rather confusing. I attempted to use an editor that was supposed to handle Bootstrap, but it doesn't recognize this.
