### ISSUE TITLE
npm: Exit status 137

### ISSUE THREAD

**Issue by xorith** [kasperisager/vanilla-bootstrap#164]
> jonathan@wurmly:/var/www/wurmly.com/vanilla/themes/bootstrap$ cat npm-debug.log
0 info it worked if it ends with ok
1 verbose cli [ '/usr/bin/node', '/usr/bin/npm', 'run', 'build' ]
2 info using npm@1.4.28
3 info using node@v0.10.38
4 verbose node symlink /usr/bin/node
5 verbose run-script [ 'prebuild', 'build', 'postbuild' ]
6 info prebuild vanilla-bootstrap@
7 info build vanilla-bootstrap@
8 verbose unsafe-perm in lifecycle true
9 info vanilla-bootstrap@ Failed to exec build script
10 error vanilla-bootstrap@ build: `gulp`
10 error Exit status 137
11 error Failed at the vanilla-bootstrap@ build script.
11 error This is most likely a problem with the vanilla-bootstrap package,
11 error not with npm itself.
11 error Tell the author that this fails on your system:
11 error     gulp
11 error You can get their info via:
11 error     npm owner ls vanilla-bootstrap
11 error There is likely additional logging output above.
12 error System Linux 3.13.0-43-generic
13 error command "/usr/bin/node" "/usr/bin/npm" "run" "build"
14 error cwd /var/www/wurmly.com/vanilla/themes/bootstrap
15 error node -v v0.10.38
16 error npm -v 1.4.28
17 error code ELIFECYCLE
18 verbose exit [ 1, true ]

This is the output of npm-debug.log. Please let me know if I need to provide any other information.

**Comment by kasperisager** [comment]
Did you run `npm install` prior to running the build?

**Comment by xorith** [comment]
Yes I did.

>jonathan@wurmly:/var/www/wurmly.com/vanilla/themes/bootstrap$ npm install
> vanilla-bootstrap@ install /var/www/wurmly.com/vanilla/themes/bootstrap
> bower install

**Comment by xorith** [comment]
For what its worth, I'm using a version of Node.js that I installed after adding the Node PPA to my Ubuntu system. 

>jonathan@wurmly:/var/www/wurmly.com/vanilla/themes/bootstrap$ node -v
v0.10.38
jonathan@wurmly:/var/www/wurmly.com/vanilla/themes/bootstrap$ npm -v
1.4.28
jonathan@wurmly:/var/www/wurmly.com/vanilla/themes/bootstrap$ 

If that helps at all.

**Comment by kasperisager** [comment]
You may want to try updating to Node 0.12.x in that case. By the way, is there a reason why you need to re-compile the theme assets on what appears to be a live site?

**Comment by xorith** [comment]
I will try that - I will likely go the route of using nvm. Also, it's not entirely live yet. I bought a domain on sale and am using a free trial period to get things going. I haven't really dabbled in server administration in a few years, so I'm a little rusty. That, and things have changed quite a bit.

**Comment by kasperisager** [comment]
Ah, gotcha! Unless you changed any of the source files there's no need to re-compile them though; the theme is good to go out of the box :+1:

**Comment by xorith** [comment]
I was following the install instructions on the vanillaforums.org add-on page. I must have overlooked that. I'll probably be making changes in the future though, so it would be good to sort out issues like these now - before the site does go live. :)

**Comment by kasperisager** [comment]
Sounds good! Let me know how things work out.

**Comment by xorith** [comment]
Running 0.12.2, still having the same issue. 
>jonathan@wurmly:/var/www/wurmly.com/vanilla/themes/bootstrap$ npm run build
>
> vanilla-bootstrap@ build /var/www/wurmly.com/vanilla/themes/bootstrap
> gulp
>
[15:20:58] Using gulpfile /var/www/wurmly.com/vanilla/themes/bootstrap/gulpfile.js
[15:20:58] Starting 'styles'...
[15:20:59] Starting 'scripts'...
Killed
>
npm ERR! Linux 3.13.0-43-generic
npm ERR! argv "/home/jonathan/.nvm/versions/v0.12.2/bin/node" "/home/jonathan/.nvm/versions/v0.12.2/bin/npm" "run" "build"
npm ERR! node v0.12.2
npm ERR! npm  v2.7.4
npm ERR! code ELIFECYCLE
npm ERR! vanilla-bootstrap@ build: `gulp`
npm ERR! Exit status 137
npm ERR! 
npm ERR! Failed at the vanilla-bootstrap@ build script 'gulp'.
npm ERR! This is most likely a problem with the vanilla-bootstrap package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     gulp
npm ERR! You can get their info via:
npm ERR!     npm owner ls vanilla-bootstrap
npm ERR! There is likely additional logging output above.
>
npm ERR! Please include the following file with any support request:
npm ERR!     /var/www/wurmly.com/vanilla/themes/bootstrap/npm-debug.log

**Comment by kasperisager** [comment]
My best bet is that something on the server is killing the gulp process. The LESS compilation task does eat up quite a bit of memory which may be the cause. Have you tried compiling the assets locally?

**Comment by xorith** [comment]
No, but that makes sense. It's a VPS - cheap one too. 512MB of RAM. I will give that a try.

**Comment by xorith** [comment]
Well I repeated the same steps on my desktop PC (Which is running Ubuntu 14.04 as well) and it got past that issue, so I think you're right. VPS management software is likely killing the task for eating up more resources than my cheap package allows me. Thanks for the great support! :)
