### ISSUE TITLE
Navigation/Notification Bar crops off

### ISSUE THREAD

**Issue by fonchifox** [kasperisager/vanilla-bootstrap#166]
This happens with the Forum embedded in Wordpress. 
When an user is logged-in and goes to an already visited discussion, the navigation bar gets cropped off.

What could it be?

![1](https://cloud.githubusercontent.com/assets/12128801/7340022/55b0ee96-ec38-11e4-90e2-f4e5ee36c88a.png)

**Comment by kasperisager** [comment]
Explicit support for embedding won't be provided (it was a nightmare to support in the first iteration of the theme).
