### ISSUE TITLE
Search hit item title not emphasized

### ISSUE THREAD

**Issue by dleffler** [kasperisager/vanilla-bootstrap#167]
I've tried all the theme options (swatches) for v2.5.0 and the discussion title is NOT emphasized so each discussion in a search tends to blend in with the rest. I've added the following style to the theme style.css simply to get it highlighted.

```
 .DataList .Title,
   .DataList .Title a {
   font-weight: bold!important;
 }
```

**Comment by kasperisager** [comment]
Closing as the project won't receive further updates until the release of Bootstrap 4.
