### ISSUE TITLE
Customize post attribution

### ISSUE THREAD

**Issue by thequicksilver** [kasperisager/vanilla-bootstrap#171]
I'm not entirely sure if this is a theme issue, or a general settings issue, so forgive me if it's the latter. I'm trying to sort out how to make discussions show the author's display name, rather than their username. It seems like the display name option is more intuitive given its reason for being, and maybe it could just be a theme setting for which one you prefer.

**Comment by kasperisager** [comment]
This would be related to Vanilla itself and not the theme.
