### ISSUE TITLE
Categories structure not visible in sidebar

### ISSUE THREAD

**Issue by wackydeli** [kasperisager/vanilla-bootstrap#172]
The hierarchical structure of categories is not visualized in the sidebar.
When using nested categories there is no way of recognizing the parent/child relationships because every category is rendered with the same styles. It would be great if at least "container" type categories (those that are merely "headlines" and cannot contain posts) would have an appearance different from regular categories.
This would be a good start:
```css
li.Heading {
  font-weight: bold;
}
```

**Comment by unixfox** [comment]
:+1:

**Comment by gogito** [comment]
Nice one

**Comment by Marqin** [comment]
:+1:

**Comment by kasperisager** [comment]
Closing as the project won't receive further updates until the release of Bootstrap 4.
