### ISSUE TITLE
when compiling via grunt all the bootstrap components the sign-in wont pop-up

### ISSUE THREAD

**Issue by fr3em1nd** [kasperisager/vanilla-bootstrap#175]
jQuery version 1.9.1 is needed when trying to show the sign-in because of an error, this is a fresh installation on v2.11

attached
![2015-07-19_4-39-37](https://cloud.githubusercontent.com/assets/2801155/8763488/aa255b5e-2dd0-11e5-8c19-490d13f06506.png)

**Comment by kasperisager** [comment]
This was fixed in v2.5.0 and onwards.
