### ISSUE TITLE
User-defined theme-chooser option

### ISSUE THREAD

**Issue by exetico** [kasperisager/vanilla-bootstrap#176]
Hello Kasper!

Thanks for a great option, to use bootstrap with Vanilla. I'm running a forum, where we want' to give the users an option to choose the theme by themself. We can ofc. just do it the simple way, with a small plugin there is overruling styles from the main bootstrap styles, but... Do you have any ideas about making this possible somehow?

I just bumped a small discussion at the official vanillaforum. See it here: http://vanillaforums.org/discussion/17108/let-users-choose-which-theme-they-want-to-use

I was thinking sending you a direct email, but ended up submitting an issue instead. If you like, please fell free to contact me at "til (at) exeti.co" (And yes, i normally prefer Danish).

**Comment by kasperisager** [comment]
This would a good idea for a plugin :+1:
