### ISSUE TITLE
When Building I Get : Plumber found unhandled error:  Error: no writecb in Transform class

### ISSUE THREAD

**Issue by nakroube** [kasperisager/vanilla-bootstrap#181]
When trying to Build or Watch, I get the following error;

Plumber found unhandled error:
 Error: no writecb in Transform class

Does anyone already fixed that? Thanks!

**Comment by kasperisager** [comment]
I'm unable to reproduce this. Could you give me the output of `node -v && npm -v && npm list --depth=0` run from the Bootstrap for Vanilla root directory?

**Comment by kasperisager** [comment]
Closing as the project won't receive further updates until the release of Bootstrap 4.
