### ISSUE TITLE
Small issue using the Readable theme

### ISSUE THREAD

**Issue by cjlindqvist** [kasperisager/vanilla-bootstrap#183]
Hi

thanks for a great theme for Vanilla, it looks and works great. Noticed a very small issue, with by no means is a make it or break it problem, but might be worth addressing in due time. It could be Bootswatch related, and if you prefer me filing it somewhere else, just let me know.

Anyway, the issue is this, the category text is not visible in the link on top (in the discussion template), see attached screen;
https://www.dropbox.com/s/dtzymqj0glukwm6/Sk%C3%A4rmklipp%202015-11-07%2020.57.41.png?dl=0

The text shows on hover though; 
https://www.dropbox.com/s/q35ftx3anbvsq21/Sk%C3%A4rmklipp%202015-11-07%2020.57.50.png?dl=0

Thanks again for a great theme. Readable is the version that is closest to the organisation I am developing a forum for own website looks like, so I would like to use it, but again, it's not a major issue.

Cheers

**Comment by kasperisager** [comment]
Closing as the project won't receive further updates until the release of Bootstrap 4.
