### ISSUE TITLE
Center facebook,google,...SSO

### ISSUE THREAD

**Issue by kimdenny** [kasperisager/vanilla-bootstrap#190]
The icons of my SSO logins aren't centered and the logos are upper than normal. How do I make it centered? Or is it a real issue?

**Comment by kasperisager** [comment]
Do they not look like [this](https://github.com/kasperisager/vanilla-bootstrap/issues/63#issuecomment-43705765)?

**Comment by kimdenny** [comment]
Nope/. they are smaller and not in the center.

**Comment by kasperisager** [comment]
Screenshot?

**Comment by kimdenny** [comment]
![image](https://cloud.githubusercontent.com/assets/8457324/15850020/a2e386cc-2cd0-11e6-91ec-c1ce92ea1bc3.png)

**Comment by kimdenny** [comment]
![image](https://cloud.githubusercontent.com/assets/8457324/15850027/b2d52702-2cd0-11e6-8c6d-97e2f124817b.png)

**Comment by kasperisager** [comment]
Ah, the Flatly theme does for some reason break the social buttons, yes. I'm however re-doing the theme for Bootstrap 4 at some point, so the current version won't receive further updates.
