### ISSUE TITLE
Use Background image?

### ISSUE THREAD

**Issue by ntimo** [kasperisager/vanilla-bootstrap#192]
Hi there,

I wanted to ask if its possible to add an background image to the theme? So that I can have a nicly looking background that matches the style of my main webpage :) Thank you in advance.

Thanks.
Timo

**Comment by kasperisager** [comment]
Sure thing! Have a look at https://css-tricks.com/almanac/properties/b/background-image/ for a guide on how to add background images in CSS.

**Comment by ntimo** [comment]
Well sure. I know that but do I have to add it to this theme?

**Comment by ntimo** [comment]
I mean which file? But thank you :)

**Comment by kasperisager** [comment]
You can add it here: https://github.com/kasperisager/vanilla-bootstrap/blob/master/design/custom.css

**Comment by ntimo** [comment]
Okay, I added this code to the custom.css but it does not work:
`body {
  background: url(https://somedomain.domain/background.jpg);
}`

**Comment by kasperisager** [comment]
There may be quite a few reasons as to why it doesn't work. Is your site online?

**Comment by ntimo** [comment]
Okay, now it displays the image. But the sidebar buttons look so so wrong. Here is the link https://forum.japan-in-nrw.de/

**Comment by ntimo** [comment]
sorry that the page was down, now its up and running again.

**Comment by ntimo** [comment]
I tried making the background of the page sidebar white with:
page-sidebar { background-color: #ffffff;
}
but it does not work :(

**Comment by mvilcis** [comment]
Isn’t `.page-sidebar` supposed to be a class? Like this:

```css
.page-sidebar { background-color: #fff; } 
```

**Comment by kasperisager** [comment]
I'll go ahead and close this as it not related to the theme itself but rather a very specific customisation thereof.
