### ISSUE TITLE
Install fail - bower components

### ISSUE THREAD

**Issue by firepixel** [kasperisager/vanilla-bootstrap#195]
Can't install, fails on 'npm install', bower components then missing for the build

npm WARN lifecycle vanilla-bootstrap@~install: cannot run in wd %s %s (wd=%s) vanilla-bootstrap@ bower install /var/www/vhosts/stclementsmileend.uk/httpdocs/themes/vanilla-bootstrap

**Comment by kasperisager** [comment]
This is a permission issue with your npm installation: https://github.com/npm/npm/issues/3497
