### ISSUE TITLE
The version published in Vanilla Addons site is not the last one

### ISSUE THREAD

**Issue by nikoskip** [kasperisager/vanilla-bootstrap#197]
Hi,

As the title say, the version on Vanilla Addons site doesn't have the most recent changes: https://open.vanillaforums.com/addon/bootstrap-theme

I had some problems with out-dated Gulp code, I fixed them and now I realized that those fixes are already here.

BTW, you did an awesome job with this theme!

**Comment by kasperisager** [comment]
v2.5.1 is currently the latest release, though `master` is a few commits ahead of it. However, there hasn't been a release for almost two years and since I'm no longer working with Vanilla it's unlikely that another one will happen 😕

**Comment by kasperisager** [comment]
...and thanks!
