### ISSUE TITLE
Issues installing in case-sensitive environments

### ISSUE THREAD

**Issue by nikoskip** [kasperisager/vanilla-bootstrap#198]
I looked for help about this problem at Vanilla Forums, so I'm going to link that thread and how I finally how I solved it:

https://open.vanillaforums.com/discussion/33207/vanilla-2-4b-i-cant-open-themes-page-in-dashboard

👍

**Comment by kasperisager** [comment]
Thanks!

**Comment by nikoskip** [comment]
@kasperisager you are going to fix this?

I'm kind of used to close issues when the solution is merged.

Cheers!

**Comment by kasperisager** [comment]
The theme is unfortunately no longer maintained but feel free to send a PR with a fix. As for case sensitivity in general, Vanilla is just odd and it's really not worth trying to fix 😕
