### ISSUE TITLE
Gulp error

### ISSUE THREAD

**Issue by kevadamson** [kasperisager/vanilla-bootstrap#199]
I'm running the following:

Vanilla 2.3
NPM 3.10.10
Node v6.10.3

When I build or watch I get: TypeError: themes.restore is not a function

Any ideas?

**Comment by kasperisager** [comment]
I'm unable to replicate this using Node.js 7 and npm 4. Are you using the latest `master`?

**Comment by kevadamson** [comment]
It's the one downloaded from the themes site ...

**Comment by kasperisager** [comment]
Alright, that's likely why in that case. You can try this one instead: https://github.com/kasperisager/vanilla-bootstrap/archive/master.zip

**Comment by kevadamson** [comment]
Thanks Kasper. That's worked perfectly :)
