### ISSUE TITLE
Is this theme still up to date ?

### ISSUE THREAD

**Issue by carlo-13** [kasperisager/vanilla-bootstrap#200]
Hi.

I just wanted to know if this theme is still up to date ?

Should I use github version on the one in vanillaforums ?

Thanks

**Comment by kasperisager** [comment]
Hi! I no longer update the theme published to https://open.vanillaforums.com, no. GitHub therefore contains the latest code.

**Comment by carlo-13** [comment]
ok, thank you for your answer.

Do you think your theme will be compatible with version 2.4 ?

**Comment by kasperisager** [comment]
No problem! It may or may not be compatible with 2.4 👐

**Comment by adrianspeyer** [comment]
It is compatible, FYI  and I run it on PHP 7.1 :)
