### ISSUE TITLE
Superhero panel headers - bad color

### ISSUE THREAD

**Issue by deathbeam** [kasperisager/vanilla-bootstrap#91]
So I discovered that in your custom_superhero css in panel headers you have color from un-themed Bootstrap.

EDIT: My pc is a bit slow so my GitHub client is lagging so I cannot create pull request, but enable superhero theme and look at discussions headings. It it #F5F5F5 color and it should be #485563

**Comment by kasperisager** [comment]
Closing as an issue with the Less compiler,
