### ISSUE TITLE
Prettier mobile commenting area

### ISSUE THREAD

**Issue by frdmn** [kasperisager/vanilla-bootstrap#95]
It looks a bit stuffed IMHO. A few spacers would be nice :)

![bildschirmfoto 2014-07-04 um 10 54 10](https://cloud.githubusercontent.com/assets/944459/3479855/cacef94e-0358-11e4-9738-10b130ebbe40.png)

**Comment by kasperisager** [comment]
Closing as the project won't receive further updates until the release of Bootstrap 4.
