### ISSUE TITLE
Embedded comments overlap

### ISSUE THREAD

**Issue by wilson29thid** [kasperisager/vanilla-bootstrap#96]
It seems when I embed Vanilla comments via iframe or embed.js, the alignment breaks and the elements overlap. Any idea what's wrong?

Example: http://i.imgur.com/4mOPpAB.png

**Comment by Co0olCat** [comment]
Bump

**Comment by Co0olCat** [comment]
First of all: Great theme! I like it and use it.

This is what I have used to fix the problem. I am using Style: Paper

In custom_paper.css:

Change from 
.MessageForm .Buttons {
    margin: 15px -15px -15px;
    text-align: right
}

To
.MessageForm .Buttons {
    margin: -1px 0px 20px;
    text-align: right
}

In style.css

Change from

.MessageForm .Buttons {
    margin: 15px -15px -15px;
    text-align: right
}

To

.MessageForm .Buttons { 
    text-align: right
}

Add to style.css at the end:

.Embed {
    margin-right: 1px;
}

Thank you.

Kind regards,
TY

**Comment by Co0olCat** [comment]
Great work.

Here is my fix for Style: Paper

in custom_paper.css:

At the end of the file add

.Embed {
    margin-right: 1px;
padding-bottom: 20px;
}

**Comment by kasperisager** [comment]
Closing as the project won't receive further updates until the release of Bootstrap 4.
